name: Write Text File

on:
  push:
    branches:
      - main

jobs:
  write_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
      - name: Write file
        run: |
          source env/bin/activate
          python write_file.py
      - name: Commit file
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Dedar
          author_email: devded@pm.me
          message: "Add example.txt"
          add: "example.txt"
