name: Write Text File

on:
  push:
    branches:
      - main

jobs:
  write_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
      - name: Write file
        run: |
          source env/bin/activate
          python write_file.py
      - name: Commit file
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Your Name
          author_email: your-email@example.com
          message: "Add example.txt"
          add: "example.txt"
